

    // Define a JavaScript object to hold course data
    const courseData = {
        "Diploma in Computer Science": ["2years", "Estimated Total Fees : RM 17,600 (Malaysian Student), RM33,300 (International Student)", "<strong><strong>Main Course:</strong></strong><br>- Introduction to Information Technology<br>- Programming Concepts and Design I<br>- Programming Concepts and Design II<br>- Operating Systems<br>- Web<br>- Design and Development<br>- Systems Analysis and Design<br>- Object-Oriented Programming Techniques<br>- Computer Systems Architecture<br>- Fundamentals of Computer Networks<br>- Database Development and Applications<br>- Pre-Calculus<br>- Introductory Calculus<br>- Statistics I<br>- Statistics II<br>- Discrete Mathematics<br>- Algebra<br>- Industrial Training<br><br><strong><strong>Elective Course</strong></strong><br> <strong>Elective I (Choose 1):</strong><br> - Accounting Methods I<br> - Introduction to Data Science<br> - Computer Game Studies<br> - Software Engineering<br> <strong>Elective II (Choose 1):</strong><br> - Accounting Methods II<br> - Introduction to Data Mining<br> - Computer Game Development<br> - Software Requirement and Design<br> <strong>Elective III (Choose 1):</strong><br> - Fundamentals of Artificial Intelligence<br> - Mobile Application Development<br> - GUI and Web Application Programming", "KL - Kuala Lumpur Main Campus<br>(R2/481/4/0345A)(08/28)(AA0109)<br>PG - Penang Branch Campus<br>(R2/0613/4/0354A)(09/28)(AA0139)<br>JH - Johor Branch Campus<br>(R/481/4/0761)(07/26)(MQA/FA7636)", "June"],
        "Diploma in Information Systems": ["2 years", "Estimated Total Fees : RM 17,800 (Malaysian Student), RM33,600 (International Student)", "<strong><strong>Main Course:</strong></strong><br>- Introduction to Information Technology<br>- Programming Concepts and Design I<br>- Programming Concepts and Design II<br>- Principles of Information Systems<br>- Web Design and Development<br>- Web Systems and Technologies<br>- Systems Analysis and Design<br>- Database Development and Applications<br>- Managing Information Systems<br>- Computer Systems Architecture<br>- Electronic Commerce<br>- Enterprise Resource Planning<br>- Operating Systems<br>- Fundamentals of Computer Networks<br>- Introductory Statistics<br>- Discrete Mathematics<br>- Principles of Accounting<br>- Industrial Training<br><br><strong><strong>Elective Course:</strong></strong><br> <strong>Elective 1 (Choose 1):</strong><br> - Introduction to Logistics Operations<br> - Mobile Commerce and Marketing<br> <strong>Elective 2 (Choose 1):</strong><br> - Cost Accounting<br> - Introduction to Data Science<br> <strong>Elective 3 (Choose 1):</strong><br> - Cloud Computing for Business<br> - Accounting Software Packages",  "KL - Kuala Lumpur Main Campus<br>(R2/481/4/0345A)(08/28)(AA0109)<br>PG - Penang Branch Campus<br>(R2/0613/4/0354A)(09/28)(AA0139)<br>JH - Johor Branch Campus<br>(R/481/4/0761)(07/26)(MQA/FA7636)", "June"],
        "Diploma in Information Technology": ["2 years", "Estimated Total Fees : RM 17,800 (Malaysian Student), RM33,600 (International Student)", "<strong><strong>Main Course:</strong></strong><br>- Introduction to Information Technology<br>- Programming Concepts and Design I<br>- Programming Concepts and Design II<br>- Principles of Information Systems<br>- Web Design and Development<br>- Systems Analysis and Design<br>- Object-Oriented Programming Techniques<br>- Operating Systems<br>- Computer Systems Architecture<br>- Fundamentals of Computer Networks<br>- Database Development and Applications<br>- Web Systems and Technologies<br>- GUI and Web Application Programming<br>- Introduction to Cybersecurity<br>- Calculus and Algebra<br>- Probability and Statistics<br>- Discrete Mathematics<br>- Industrial Training (10 weeks)<br><br><strong><strong>Elective Course:</strong></strong><br> <strong>Elective I (choose 1):</strong><br> - Introduction to Business<br> - Mobile Commerce and Marketing<br> <strong>Elective II (choose 1):</strong><br> - Introduction to Marketing<br> - Introduction to Data Science<br> <strong>Elective III (choose 1):</strong><br> - Business Organisation and Management<br> - Cloud Computing for Business","KL - Kuala Lumpur Main Campus<br>(R2/481/4/0345A)(08/28)(AA0109)<br>PG - Penang Branch Campus<br>(R2/0613/4/0354A)(09/28)(AA0139)<br>JH - Johor Branch Campus<br>(R2/0611/4/0199A)(09/28)(AA0163)<br>PH - Pahang Branch<br>(R2/0611/4/0198A)(12/28)(AA0168)<br>SB - Sabah Branch<br>(R2/0611/4/0197A)(12/28)(AA0122)", "June"],
        "Diploma in Software Engineering": ["2 years", "Estimated Total Fees : RM 17,800 (Malaysian Student)", "<strong><strong>Main Course:</strong></strong><br>- Problem Solving and Programming<br>- Software Engineering<br>- Calculus and Algebra<br>- Software Requirement and Design<br>- Web Design and Development<br>- Object-Oriented Programming Techniques<br>- Software Testing and Quality<br>- Database Development and Applications<br>- Computer Systems Architecture<br>- Software Maintenance<br>- Operating Systems<br>- Mini Project<br>- Introduction to Data Structures and Algorithms<br>- Discrete Mathematics<br>- Mobile Application Development<br>- Fundamentals of Computer Networks<br>- Industrial Training (10 weeks)<br><br><strong><strong>Elective Course:</strong></strong><br> <strong>Electives (Choose 2):</strong><br> - Introduction to Artificial Intelligence<br> - Introduction to Cloud Computing<br> - Introduction to Data Science<br> - Electronic Commerce","SB - Sabah Branch<br>(R2/0611/4/0197A)(12/28)(AA0122)", "June"],
        "Bachelor of Science (Honours) in Management Mathematics with Computing": ["3 years", "Estimated Total Fees : RM 34,100 (Malaysian Student), RM59,500 (International Student)", "<strong><strong>Main Course:</strong></strong><br>- Discrete Mathematics<br>- Calculus I<br>- Calculus II<br>- Algebra<br>- Probability and Statistics<br>- Linear Algebra<br>- Advanced Calculus<br>- Numerical Methods<br>- Mathematical and Statistical Software<br>- Problem Solving and Programming<br>- Database Management<br>- Computer Organisation and Architecture<br>- Object-Oriented Programming<br>- Operating Systems<br>- IT Fundamentals<br>- Visual Programming<br>- Industrial Training<br>- Project<br>- Mathematical Statistics<br>- Applied Statistics<br>- Operations Research I<br>- Operations Research II<br>- Financial Mathematics<br>- Quality Control<br>- Contemporary Malaysian Issues<br><br><strong><strong>Elective Course:</strong></strong><br> <strong>Elective 1A and 1B (Choose 2):</strong><br> - Microeconomics<br> - Macroeconomics<br> - Accounting Methods I<br> - Accounting Methods II<br> <strong>Elective (Mathematics)(Choose 1):</strong><br> - Further Applied Statistics<br> - Cryptography<br> - Advanced Financial Mathematics<br> <strong>Elective (ICT)(Choose 1):</strong><br> - Machine Learning<br> - Cloud Computing<br> - Business Intelligence<br> - Data Science","KL - Kuala Lumpur Main Campus<br>(R2/481/4/0345A)(08/28)(AA0109)", "Year 1 Intake: June<br>Year 2 Intake: June"],
        "Bachelor of Computer Science (Honours) in Interactive Software Technology": ["3 years", "Estimated Total Fees : RM 35,100 (Malaysian Student), RM61,200 (International Student)", "<strong><strong>Main Course:</strong></strong><br>- Problem Solving and Programming<br>- Computer Game Studies<br>- Database Management<br>- Computer Organisation and Architecture<br>- Object-Oriented Programming<br>- Research Methods<br>- Object-Oriented Analysis and Design<br>- Data Structures and Algorithms<br>- Operating Systems<br>- Software Engineering<br>- Graphics Programming<br>- Computer Game Programming<br>- Social and Professional Issues<br>- Contemporary Malaysian Issues<br>- Artificial Intelligence<br>- IT Fundamentals<br>- Web Design and Development<br>- Distributed Systems and Parallel Computing<br>- Fundamentals of Computer Networks<br>- Mobile Application Development<br>- Human Computer Interaction<br>- Discrete Mathematics<br>- Probability and Statistics<br>- Mathematics for Games Technology<br>- Project I<br>- Project II<br>- Industrial Training (6 months)<br><br><strong><strong>Elective Course:</strong></strong><br> <strong>Elective 1 (Choose 1):</strong><br> - 3D Game Development<br> - 3D Animation<br> <strong>Elective 2, Elective 3 (Choose any 2):</strong><br> - Virtual Reality<br> - Computer Game Design<br> - Advanced Computer Game Programming<br> - Computer Games Technology<br> - Blockchain Application Development<br> - Digital Illustration<br> <strong>Elective 4 (Choose 1):</strong><br> - Introduction to Short Story<br> - Music Appreciation","KL - Kuala Lumpur Main Campus<br>(R2/481/4/0345A)(08/28)(AA0109)", "Year 1 Intake: June<br>Year 2 Intake: June"],
        "Bachelor of Software Engineering (Honours)": ["3 years", "Estimated Total Fees : RM 34,600 (Malaysian Student), RM60,400 (International Student)","<strong><strong>Main Course:</strong></strong><br>- Problem Solving and Programming<br>- Database Management<br>- Introduction to Computer Systems<br>- Object-Oriented Programming<br>- Research Methods<br>- Data Structures and Algorithms<br>- Software Engineering<br>- Social and Professional Issues<br>- Software Quality Assurance and Testing<br>- Software Requirements Engineering<br>- Software Design and Architecture<br>- Software Project Management<br>- Formal Methods for Software Engineering<br>- Software Evolution and Maintenance<br>- Systems Analysis and Design<br>- Introduction to Computer Networks<br>- Web Design and Development<br>- Human Computer Interaction<br>- Probability and Statistics<br>- Discrete Mathematics<br>- Advanced Discrete Mathematics<br>- Music Appreciation<br>- Project I<br>- Project II<br>- Industrial Training (6 months)<br><br><strong><strong>Elective Course:</strong></strong><br> <strong>Electives (Choose 6):</strong><br> - Advanced Database Management<br> - Artificial Intelligence<br> - Web Application Development<br> - Blockchain Application Development<br> - Introduction to Computer Security<br> - Distributed Systems and Parallel Computing<br> - Mobile Application Development<br> - Graphic Programming<br> - Integrative Programming<br> - Image Processing<br> - Data Science<br> - Cloud Computing<br> - Agile Software Development","KL - Kuala Lumpur Main Campus<br>(R2/481/4/0345A)(08/28)(AA0109)<br>PH - Pahang Branch<br>(R2/0611/4/0198A)(12/28)(AA0168)", "Year 1 Intake: January (KL); June (KL, PG); November (KL)<br>Year 2 Intake: June (KL, PG)"],
        "Bachelor of Computer Science (Honours) in Data Science": ["3 years", "Estimated Total Fees : RM34,300 (Malaysian Student), RM59,900 (International Student)", "<strong><strong>Main Course:</strong></strong><br>- Introduction to Computer Systems<br>- Web Design and Development<br>- Software Engineering<br>- Natural Language Processing<br>- Introduction to Computer Networks<br>- Data Science<br>- Statistics for Data Science<br>- Artificial Intelligence<br>- Machine Learning<br>- Data Engineering<br>- Data Visualisation<br>- Data Warehouse Technology<br>- Cloud Computing<br>- Problem Solving and Programming<br>- Database Management<br>- Advanced Database Management<br>- Object-Oriented Programming<br>- Research Methods<br>- Data Structures and Algorithms<br>- Social and Professional Issues<br>- Probability and Statistics<br>- Discrete Mathematics<br>- Project I<br>- Project II<br>- Industrial Training (6 months)<br><br><strong><strong>Elective Course:</strong></strong><br> <strong>Elective 1 (Choose 1):</strong><br> - Introduction to Computer Security<br> - Mobile Application Development<br> <strong>Elective 2 (Choose 1):</strong><br> - Principle of Marketing<br> - Business Organisation and Management<br> <strong>Elective 3 (Choose 1):</strong><br> - Internet of Things<br> - Graphics Programming<br> - Distributed Systems and Parallel Computing<br> <strong>Elective 4 (Choose 1):</strong><br> - Image Processing<br> - Algebra and Calculus<br> - Blockchain Application Development","KL - Kuala Lumpur Main Campus<br>(R2/481/4/0345A)(08/28)(AA0109)<br>PG - Penang Branch Campus<br>(N/481/6/0815)(06/24)(MQA/PA10813)", "Year 1 Intake: January (KL); June (KL, PG); November (KL)<br>Year 2 Intake: June (KL, PG)"]
    };
    
   // Get references to the course selection elements and the comparison data cells
const courseSelectElements = {
    top1: document.getElementById('courseSelectTop1'),
    top2: document.getElementById('courseSelectTop2'),
};

const attributeCells = {
    first: [
        document.getElementById('firstAttribute'),
        document.getElementById('firstAttribute2'),
        document.getElementById('firstAttribute3'),
        document.getElementById('firstAttribute4'),
        document.getElementById('firstAttribute5'),
    ],
    third: [
        document.getElementById('thirdAttribute'),
        document.getElementById('thirdAttribute2'),
        document.getElementById('thirdAttribute3'),
        document.getElementById('thirdAttribute4'),
        document.getElementById('thirdAttribute5'),
    ],
};

// Event listeners to update comparison table when a course is selected
courseSelectElements.top1.addEventListener('change', () => {
    updateComparisonTable(courseSelectElements.top1, 'first');
});

courseSelectElements.top2.addEventListener('change', () => {
    updateComparisonTable(courseSelectElements.top2, 'third');
});

function updateComparisonTable(selectedCourseElement, column) {
    const selectedCourse = selectedCourseElement.value;
    const courseAttributes = courseData[selectedCourse];

    if (courseAttributes) {
        // Update the corresponding column based on the selected course
        const attributeCell = attributeCells[column];

        for (let i = 0; i < courseAttributes.length; i++) {
            attributeCell[i].innerHTML = courseAttributes[i];
        }
    } else {
        // Clear the comparison table when no course is selected
        const attributeCell = attributeCells[column];

        for (let i = 0; i < attributeCell.length; i++) {
            attributeCell[i].innerHTML = '';
        }
    }
}
